apiVersion: v1
kind: ConfigMap
metadata:
  name: app-db-config
  labels:
    app: app
data:
  DATABASE_HOST: postgres-db-lb.postgres.svc.cluster.local
  DATABASE_NAME: "postgres"
  DATABASE_USER: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_PASS: "mysecretpassword"